builders:
  data_class_builder:
    import: "package:darta/builder.dart"
    builder_factories: ["dataClassBuilder"]
    build_extensions: {".dart": ["data.p.dart"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]